[#123] Create Sidebar
jorgecoutinhobr/school-on-rails pull request #5
Opened 2024-05-22 00:17 UTC by jorgecoutinhobr

- Add Flowbite 
- Add Sidebar
- Add Home_controller
- Add tailwind typography

2024-05-22 01:05 UTC, guilhermemendonca08 approved these changes

2024-05-22 02:09 UTC, bc-nogueira requested changes
The sidebar is looking good!
I left 2 small change requests that are really simple. Other than that, well done!

2024-05-22 02:09 UTC, bc-nogueira commented on app/javascript/application.js
> +import 'flowbite/dist/datepicker.turbo.js';
Let's keep a pattern when using quotes. Since it's a js file we can use double quotes so please change line 5 to use double quotes.

2024-05-22 02:09 UTC, bc-nogueira commented on app/views/layouts/application.html.erb
> +  <body class=" bg-gray-100 dark:bg-gray-900">
There is a space between the opening quotes and the first class.

2024-05-23 00:27 UTC, bc-nogueira approved these changes
Good job!

2024-05-23 00:31 UTC, merged